global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "document-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "processing-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["host.docker.internal:8082"]

  - job_name: "export-job-service"
    metrics_path: "/q/metrics"
    static_configs:
      - targets: ["host.docker.internal:8083"]