server:
  port: 8081

spring:
  application:
    name: document-service

  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/documentsdb}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cloud:
    stream:
      bindings:
        documentSubmitted-out-0:
          destination: document-submitted
          content-type: application/json
      kafka:
        binder:
          brokers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} level=%-5level service=${spring.application.name} traceId=%X{traceId} spanId=%X{spanId} correlationId=%X{correlationId} documentId=%X{documentId} thread=%thread logger=%logger{36} msg=\"%msg\"%n"