quarkus.http.port=8083

processing-service/mp-rest/url=${PROCESSING_SERVICE_URL:http://localhost:8082}

export.path=${EXPORT_PATH:./exports}

quarkus.scheduler.enabled=true

quarkus.micrometer.export.prometheus.enabled=true

quarkus.smallrye-health.root-path=/q/health
quarkus.micrometer.export.prometheus.path=/q/metrics

quarkus.otel.enabled=true
quarkus.otel.service.name=export-job-service
quarkus.otel.traces.exporter=otlp
quarkus.otel.exporter.otlp.traces.endpoint=${OTEL_EXPORTER_OTLP_TRACES_ENDPOINT:http://localhost:4317}
quarkus.otel.resource.attributes=service.name=export-job-service

quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss.SSS} level=%p service=export-job-service traceId=%X{traceId} spanId=%X{spanId} correlationId=%X{correlationId} jobName=%X{jobName} thread=%t logger=%c{2.} msg="%s"%n