quarkus.http.port=8083

processing-service/mp-rest/url=${PROCESSING_SERVICE_URL:http://localhost:8082}

export.path=${EXPORT_PATH:./exports}

quarkus.scheduler.enabled=true

quarkus.micrometer.export.prometheus.enabled=true

quarkus.smallrye-health.root-path=/q/health
quarkus.micrometer.export.prometheus.path=/q/metrics